### ISSUE TITLE
Create Workout-Card

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#1]
**Value proposition (user story)**

As a **user**
I want to **see the description of a give workout**
in order to **select the wished workout and become a music playlist that matchs the workout.** 

**Description (text, scribble, design)**

![Screenshot 2021-03-05 at 15 53 54](https://user-images.githubusercontent.com/19183204/110132311-53a3aa00-7dcb-11eb-87a5-c07e634bcdb4.png)

- 1 card
- Text : description of a workout 

**Acceptance criteria (edge cases)**

- [x] styled as briefly designed
- [x] the card is open when the list appears

**Complexity (S, M, L)**
S

**Tasks**

- [x] Create feature branch
- [x] Add example of workout
- [x] Add application logic
- [x] Create Card component (storybook)
- [x] Test the components
