### ISSUE TITLE
Get a playlist

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#10]
**Value statement**

As a **user**
I need **to see the playlist created for my workout**
so that **I can meet my basic expectation for this app**

**Description (Text, Scribble, Wireframe, Design)**

![Screenshot 2021-03-14 at 14 01 03](https://user-images.githubusercontent.com/19183204/111069598-17a8cd00-84ce-11eb-83e5-a141b580e7e1.png)

**Acceptance criteria**
- [x] By click on get a playlist the page playlist is shown 
- [x] The playlist page shows the desired workout and the matching song for each section

**Tasks**

- [x] Create a button component (get a playlist)
- [x] Add logic to form (link data from workout and music)
- [x] Styling
- [x] Storybook component
- [x] Tests
