### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#14]
**Value statement**

As a **user**
I need **to navigate around the app**
so that **I can easily find my way around**

**Description (Text, Scribble, Wireframe, Design)**

ADD

**Acceptance criteria**
- [x] By clicking home the user can start selecting a workout
- [x] By clicking bookmarks the user can see the saved workouts

**Tasks**

- [x] Create a nav component with two buttons
- [x] Add logic to the nav
- [x] Styling
- [x] Storybook component
- [x] Tests
