### ISSUE TITLE
Download Playlist as PDF

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#15]
**Value statement**

As a **user**
I need **to save the playlist created for my workout**
so that **I can make use of the information in another time**

**Description (Text, Scribble, Wireframe, Design)**

ADD screenshot

**Acceptance criteria**
- [ ] By click on the get PDF Button, the list should be saved 

**Tasks**

- [ ] Create a button component (get a playlist as PDF)
- [ ] Add logic to the button
- [ ] Styling
- [ ] Storybook component
- [ ] Tests

**Complexity**
M
