### ISSUE TITLE
Bookmark a playlist

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#16]
**Value statement**

As a **user**
I need **to save the playlist created for my workout**
so that **I can make use of the information in another time**

**Description (Text, Scribble, Wireframe, Design)**

ADD screenshot

**Acceptance criteria**
- [x] By click on the bookmark icon, the list should be saved 

**Tasks**

- [x] Add an icon (role=button) component
- [x] Add logic to the button
- [x] Styling
- [x] Storybook component
- [x] Tests

**Complexity**
S
