### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#17]
**Value statement**

As a **user**
I need **to get some initial information about the app**
so that **I can feel welcome and got a initial idea of what is in the app there for me**

**Description (Text, Scribble, Wireframe, Design)**

ADD screenshot

**Acceptance criteria**
- [x] Initial information about the app is displayed
- [x] Button to start the app

**Tasks**

- [x] Create a button component (Start)
- [x] Add logic to the button
- [x] Styling
- [x] Storybook component
- [x] Tests

**Complexity**
M
