### ISSUE TITLE
Toogle Workout-Card-description

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#2]
**Value proposition (user story)**

As a **user**
I need to **not see all the workout descriptions at once**
so that **I don´t get overwhelmed with so much info**

**Description (Text, Scribble, Wireframe, Design)**
<img width="297" alt="Screenshot 2021-03-05 at 15 28 37" src="https://user-images.githubusercontent.com/19183204/110128840-8b105780-7dc7-11eb-91e8-2e2dcea28662.png">

**Acceptance criteria**

- [x]  Answer is hidden by default
- [x] Button text changes on tap
- [x] Each cards expands in place

**Complexity (S, M, L)**
S

**Tasks**

- [x] Create button component
- [x] Add toggle logic
- [x] Minimal styling
- [x] Test with a few cards on mobile and desktop
