### ISSUE TITLE
Add color to Workout-Card-description

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#3]
**Value proposition (user story)**

As a **user**
I need to **visually identify the subsections and the intensity of a workout **
so that **I can get a quick glance of the energy levels expected by each workout subsection**

**Description (Text, Scribble, Wireframe, Design)**
<img width="299" alt="Screenshot 2021-03-05 at 15 30 23" src="https://user-images.githubusercontent.com/19183204/110129038-c14dd700-7dc7-11eb-91cf-2bddc16e4bbd.png">

**Acceptance criteria**

- [x]  Blocks with usual colors 
- [x] Blocks for three workout sections (warm-up, main, cooldown)

**Complexity (S, M, L)**
S

**Tasks**

- [x] Add grid
- [x] Finish styling
- [x] Test with a few cards on mobile and desktop
