### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#4]
**Value proposition (user story)**

As a **user**
I need to **identy in what page I am currently on**
so that **I can have a better user experience

**Description (Text, Scribble, Wireframe, Design)**
<img width="293" alt="Screenshot 2021-03-05 at 15 31 24" src="https://user-images.githubusercontent.com/19183204/110129126-e2aec300-7dc7-11eb-8a76-93b10768bef6.png">

**Acceptance criteria**

- [x]  Centered text
- [x] Header position

**Complexity (S, M, L)**
S

**Tasks**

- [x] Add App-grid
- [x] Do minimal styling
- [x] Create Card component (storybook)
- [x] Run a test
