### ISSUE TITLE
Linking two pages

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#8]
**Value statement**

As a **user**
I need **a way to select a desired workout and move to the next step**
so that **I can specify other filters before getting my playlist**

**Description (Text, Scribble, Wireframe, Design)**

![Screenshot 2021-03-14 at 13 59 58](https://user-images.githubusercontent.com/19183204/111069573-fb0c9500-84cd-11eb-9627-f635632201c2.png)

**Acceptance criteria**
- [x] By click on select this workout the card turn to is selected
- [x] By click next the page music is shown 
- [x] The music page shows a small view of the desired workout
- [x] The music page has back button

**Tasks**

- [x] Create button components (select this workout & next)
- [x] Add logic to the bookmark (select this workout)
- [x] Create the music page 
- [x] Add logic for the next button (links to the music page)
- [x] Add logic for the back button (links to the workout page)
- [x] Storybook components
- [x] Tests

**Complexity**
M
