### ISSUE TITLE
Filter for music, decade and energy

### ISSUE THREAD

**Issue by BerePendzialek** [BerePendzialek/capstone-project#9]
### Value statement

As a **user**
I need **to filter the possible music tracks**
so that **I can get a more personalized playlist**

**Description (Text, Scribble, Wireframe, Design)**

![Screenshot 2021-03-14 at 14 00 48](https://user-images.githubusercontent.com/19183204/111069579-09f34780-84ce-11eb-9f35-32957c1dcaad.png)

**Acceptance criteria**
- [x] Dropdown menus for genre, decade and energy show the categories according to the data structure

**Tasks**

- [x] Create input components 
- [x] Create a static music .JSON file in order to show the track options (data should be presented like the spotify API)
- [x] Add logic to the filters
- [x] Storybook component
- [x] Tests

**Complexity**
M
